### ISSUE TITLE
Amendment proposal: Adding the code of conduct as an appendix

### ISSUE THREAD

**Issue by FromAnkyra** [HackSoc/constitution#15]
Best way to do this imo is to add it to the end of section 5: Code of practice, replacing point 14

> In addition:
> Members must follow the code of conduct for use of Society chat systems (e.g. IRC, Slack, etc.);
> Members making use of HackSoc-provided servers must follow any applicable acceptable use policies.

Unless someone has a better place to put it. Also, does anyone have strong opinions on whether said appendix should be redone in markdown, or whether we should just reference the webpage?

**Comment by markspolakovs** [comment]
Added as of #16, approved at the October 2021 EGM. Closing this issue.
