### ISSUE TITLE
Amendment Proposal: Hoodie Names

### ISSUE THREAD

**Issue by JMAlego** [HackSoc/constitution#6]
For a while now we have had a policy that, if the name on a HackSoc member's hoodie is no longer correct, we will give them a replacement hoodie with the correct name on it next time there is an order (typically when a new committee is elected) without them needing to pay for it to be replaced. It would be good to formalise this into the constitution (or into another governing document, say an appendix) to continue this policy to future committees.

I'm personally not sure where this would fit in the constitution (or other documents) so would like input from the people who care/know about these things (e.g. the secretaries @sersorrel  and @adambirtles).

**Comment by sersorrel** [comment]
am vaguely +1 on some separate policy document for stuff like this. constitutional amendments are Pain, and in general I'm in favour of keeping the constitution a) reasonably short and b) as close as possible to what YUSU is expecting.

(presumably the appeal of doing it as a constitutional amendment is to make it a similar amount of Pain for a future committee to undo it? but it still feels odd to have "we will have a chair, a secretary, a treasurer, ..." in the same document as "if and when we buy hoodies, we should make sure to give an updated one to anyone who's changed their name")

the question then I guess is "where does that policy document live", if it lives in this repo we should revisit and clarify the contribution instructions in README.md to make it very clear how and when which files can be modified.

**Comment by JMAlego** [comment]
I like the idea of stuff like this living in Appendices (which are a concept that I think @adambirtles is working on right now). If the amendment to add appendices goes ahead then they would be a good place for this I think...
